### ISSUE TITLE
Error at using beast('lights' ).set(power: "off")

### ISSUE THREAD

**Issue by cayrodmed1** [netbeast-co/nb-resources#9]
I've discovered that you can't use `power: "off"` while turning `lights` off (didn't try with other topics). If you want to turn power off, you have to use `power: false` in the `set` method. It doesn't happen while turning lights on, they both work `power: "on"` and `power: true`.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/131979095212100/131998251682174)

**Comment by jsdario** [comment]
You are not the first one in experiencing this issue. This _probably_ has to do with the virtual bulb plugin. I'll assign @pablopi  but also I'll try to check it tomorrow myself. If you want to help please take a look on this line which might be the problem.

https://github.com/netbeast/bulb-plugin/blob/master/plugin.js#L80
